sudo: required
services:
  - docker

before_install:
  - docker build -t kthrix/minimal-iw-wp2st -f ./minimal-iw-wp2st/Dockerfile ./minimal-iw-wp2st

after_success:
  - docker build -t kthrix/minimal-iw-wp2st ./minimal-iw-wp2st_nginx
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images, and push them to docker hub
  - docker push dreybo/minimal-iw-wp2st

